version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - ./backend:/app
      - /app/node_modules
#    ports:
#      - "3001:3001"
    restart: on-failure
    command: sh -c "npm run start:dev"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "mar-2023"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client:/usr/share/nginx/html
    restart: on-failure


  redis:
    image: redis:alpine
    restart: on-failure

